package controller;

import java.util.ArrayList;
import java.util.List;

import model.Film;
import model.Genere;

public class Videoteca {
	
	private static List<Film> elencoFilm = new ArrayList<>();
	static{
		elencoFilm.add(new Film("Il padrino","Francis Ford Coppola",Genere.AZIONE,1972));
		elencoFilm.add(new Film("I predatori dell arca perduta","Steven Spielberg",Genere.AZIONE,1981));
		elencoFilm.add(new Film("LImpero colpisce ancora","Irvin Kershner",Genere.AZIONE,1980));
		elencoFilm.add(new Film("Le ali della libertà","Frank Darabont",Genere.AZIONE,1994));
		elencoFilm.add(new Film("Lo squalo","Steven Spielberg",Genere.AZIONE,1975));
		elencoFilm.add(new Film("Quei bravi ragazzi","Martin Scorsese",Genere.AZIONE,1990));
		elencoFilm.add(new Film("Apocalypse Now","Francis Ford Coppola",Genere.AZIONE,1979));
		elencoFilm.add(new Film("Cantando sotto la pioggia","Stanley Donen e Gene Kelly",Genere.AZIONE,1952));
		elencoFilm.add(new Film("Pulp Fiction","Quentin Tarantino",Genere.AZIONE,1994));
		elencoFilm.add(new Film("Fight Club","David Fincher",Genere.AZIONE,1999));
		elencoFilm.add(new Film("Toro scatenato","Martin Scorsese",Genere.AZIONE,1980));
		elencoFilm.add(new Film("L appartamento","Billy Wilder",Genere.AZIONE,1960));
		elencoFilm.add(new Film("Chinatown","Roman Polański",Genere.AZIONE,1974));
		elencoFilm.add(new Film("C era una volta il West","Sergio Leone",Genere.AZIONE,1968));
		elencoFilm.add(new Film("Il cavaliere oscuro","Christopher Nolan",Genere.AZIONE,2008));
		elencoFilm.add(new Film("2001: Odissea nello spazio","Stanley Kubrick",Genere.AZIONE,1968));
		elencoFilm.add(new Film("Taxi Driver","Martin Scorsese",Genere.AZIONE,1976));
		elencoFilm.add(new Film("Casablanca","Michael Curtiz",Genere.AZIONE,1942));
		elencoFilm.add(new Film("Il padrino - Parte II","Francis Ford Coppola",Genere.AZIONE,1974));
		elencoFilm.add(new Film("Blade Runner","Ridley Scott",Genere.AZIONE,1982));
		elencoFilm.add(new Film("Il terzo uomo","Carol Reed",Genere.AZIONE,1949));
		elencoFilm.add(new Film("Guerre stellari","George Lucas",Genere.AZIONE,1977));
		elencoFilm.add(new Film("Ritorno al futuro","Robert Zemeckis",Genere.AZIONE,1985));
		elencoFilm.add(new Film("Il Signore degli Anelli - La Compagnia dell Anello","Peter Jackson",Genere.AZIONE,2001));
		elencoFilm.add(new Film("Il buono, il brutto, il cattivo","Sergio Leone",Genere.AZIONE,1966));
		elencoFilm.add(new Film("Il dottor Stranamore - Ovvero: come ho imparato a non preoccuparmi e ad amare la bomba","Stanley Kubrick",Genere.AZIONE,1964));
		elencoFilm.add(new Film("A qualcuno piace caldo","Billy Wilder",Genere.AZIONE,1959));
		elencoFilm.add(new Film("Quarto potere","Orson Welles",Genere.AZIONE,1941));
		elencoFilm.add(new Film("Trappola di cristallo","John McTiernan",Genere.AZIONE,1988));
		elencoFilm.add(new Film("Aliens - Scontro finale","James Cameron",Genere.AZIONE,1986));
		elencoFilm.add(new Film("Via col vento","Victor Fleming, George Cukor, Sam Wood",Genere.AZIONE,1939));
		elencoFilm.add(new Film("Butch Cassidy","George Roy Hill",Genere.AZIONE,1969));
		elencoFilm.add(new Film("Alien","Ridley Scott",Genere.AZIONE,1979));
		elencoFilm.add(new Film("Il Signore degli Anelli - Il ritorno del re","Peter Jackson",Genere.AZIONE,2003));
		elencoFilm.add(new Film("Terminator 2 - Il giorno del giudizio","James Cameron",Genere.AZIONE,1991));
		elencoFilm.add(new Film("Andrej Rublëv","Andrej Tarkovskij",Genere.AZIONE,1969));
		elencoFilm.add(new Film("Arancia meccanica","Stanley Kubrick",Genere.AZIONE,1971));
		elencoFilm.add(new Film("Heat - La sfida","Michael Mann",Genere.AZIONE,1995));
		elencoFilm.add(new Film("Matrix","Lana e Lilly Wachowski",Genere.AZIONE,1999));
		elencoFilm.add(new Film("La donna che visse due volte","Alfred Hitchcock",Genere.AZIONE,1958));
		elencoFilm.add(new Film("I 400 colpi","François Truffaut",Genere.AZIONE,1959));
		elencoFilm.add(new Film("Sangue blu","Robert Hamer",Genere.AZIONE,1949));
		elencoFilm.add(new Film("Il grande Lebowski","Joel ed Ethan Coen",Genere.AZIONE,1998));
		elencoFilm.add(new Film("Schindler s List - La lista di Schindler","Steven Spielberg",Genere.AZIONE,1993));
		elencoFilm.add(new Film("Psyco","Alfred Hitchcock",Genere.AZIONE,1960));
		elencoFilm.add(new Film("Fronte del porto","Elia Kazan",Genere.AZIONE,1954));
		elencoFilm.add(new Film("E.T. l extra-terrestre","Steven Spielberg",Genere.AZIONE,1982));
		elencoFilm.add(new Film("This Is Spinal Tap","Rob Reiner",Genere.AZIONE,1984));
		elencoFilm.add(new Film("La casa 2","Sam Raimi",Genere.AZIONE,1987));
		elencoFilm.add(new Film("I sette samurai","Akira Kurosawa",Genere.AZIONE,1954));
		elencoFilm.add(new Film("8½","Federico Fellini",Genere.AZIONE,1963));
		elencoFilm.add(new Film("Shining","Stanley Kubrick",Genere.AZIONE,1980));
		elencoFilm.add(new Film("Donnie Darko","Richard Kelly",Genere.AZIONE,2001));
		elencoFilm.add(new Film("Il Signore degli Anelli - Le due torri","Peter Jackson",Genere.AZIONE,2002));
		elencoFilm.add(new Film("La dolce vita","Federico Fellini",Genere.AZIONE,1960));
		elencoFilm.add(new Film("Casino Royale","Martin Campbell",Genere.AZIONE,2006));
		elencoFilm.add(new Film("Lawrence d Arabia","David Lean",Genere.AZIONE,1962));
		elencoFilm.add(new Film("La signora del venerdì","Howard Hawks",Genere.AZIONE,1940));
		elencoFilm.add(new Film("Incontri ravvicinati del terzo tipo","Steven Spielberg",Genere.AZIONE,1977));
		elencoFilm.add(new Film("Va e vedi","Elem Klimov",Genere.AZIONE,1985));
		elencoFilm.add(new Film("I soliti sospetti","Bryan Singer",Genere.AZIONE,1995));
		elencoFilm.add(new Film("Il laureato","Mike Nichols",Genere.AZIONE,1967));
		elencoFilm.add(new Film("Viale del tramonto","Billy Wilder",Genere.AZIONE,1950));
		elencoFilm.add(new Film("Old Boy","Park Chan-wook",Genere.AZIONE,2003));
		elencoFilm.add(new Film("Harold e Maude","Hal Ashby",Genere.AZIONE,1971));
		elencoFilm.add(new Film("Edward mani di forbice","Tim Burton",Genere.AZIONE,1990));
		elencoFilm.add(new Film("Viaggio a Tokyo","Yasujirō Ozu",Genere.AZIONE,1953));
		elencoFilm.add(new Film("Io e Annie","Woody Allen",Genere.AZIONE,1977));
		elencoFilm.add(new Film("Tre colori - Film rosso","Krzysztof Kieślowski",Genere.AZIONE,1994));
		elencoFilm.add(new Film("Stand by Me - Ricordo di un estate","Rob Reiner",Genere.AZIONE,1986));
		elencoFilm.add(new Film("La morte corre sul fiume","Charles Laughton",Genere.AZIONE,1955));
		elencoFilm.add(new Film("La parola ai giurati","Sidney Lumet",Genere.AZIONE,1957));
		elencoFilm.add(new Film("Se mi lasci ti cancello","Michel Gondry",Genere.AZIONE,2004));
		elencoFilm.add(new Film("Il tesoro della Sierra Madre","John Huston",Genere.AZIONE,1948));
		elencoFilm.add(new Film("Scala al paradiso","Michael Powell e Emeric Pressburger",Genere.AZIONE,1946));
		elencoFilm.add(new Film("Manhattan","Woody Allen",Genere.AZIONE,1979));
		elencoFilm.add(new Film("Spartacus","Stanley Kubrick",Genere.AZIONE,1960));
		elencoFilm.add(new Film("Rosemary s Baby - Nastro rosso a New York","Roman Polański",Genere.AZIONE,1968));
		elencoFilm.add(new Film("La sottile linea rossa","Terrence Malick",Genere.AZIONE,1998));
		elencoFilm.add(new Film("Duello a Berlino","Michael Powell e Emeric Pressburger",Genere.AZIONE,1943));
		elencoFilm.add(new Film("Batman Begins","Christopher Nolan",Genere.AZIONE,2005));
		elencoFilm.add(new Film("La grande fuga","John Sturges",Genere.AZIONE,1963));
		elencoFilm.add(new Film("Brazil","Terry Gilliam",Genere.AZIONE,1985));
		elencoFilm.add(new Film("L.A. Confidential","Curtis Hanson",Genere.AZIONE,1997));
		elencoFilm.add(new Film("Velluto blu","David Lynch",Genere.AZIONE,1986));
		elencoFilm.add(new Film("Carrie - Lo sguardo di Satana","Brian De Palma",Genere.AZIONE,1976));
		elencoFilm.add(new Film("Re per una notte","Martin Scorsese",Genere.AZIONE,1983));
		elencoFilm.add(new Film("Una pazza giornata di vacanza","John Hughes",Genere.AZIONE,1986));
		elencoFilm.add(new Film("Magnolia","Paul Thomas Anderson",Genere.AZIONE,1999));
		elencoFilm.add(new Film("Harry, ti presento Sally...","Rob Reiner",Genere.AZIONE,1989));
		elencoFilm.add(new Film("Il ritorno dello Jedi","Richard Marquand",Genere.AZIONE,1983));
		elencoFilm.add(new Film("C era una volta in America","Sergio Leone",Genere.AZIONE,1984));
		elencoFilm.add(new Film("Lo spirito dell alveare","Víctor Erice",Genere.AZIONE,1973));
		elencoFilm.add(new Film("Il mucchio selvaggio","Sam Peckinpah",Genere.AZIONE,1969));
		elencoFilm.add(new Film("La sfida del samurai","Akira Kurosawa",Genere.AZIONE,1961));
		elencoFilm.add(new Film("American Beauty","Sam Mendes",Genere.AZIONE,1999));
		elencoFilm.add(new Film("Le iene","Quentin Tarantino",Genere.AZIONE,1992));
		elencoFilm.add(new Film("Intrigo internazionale","Alfred Hitchcock",Genere.AZIONE,1959));
		elencoFilm.add(new Film("Toy Story - Il mondo dei giocattoli","John Lasseter",Genere.AZIONE,1995));
		elencoFilm.add(new Film("Quinto potere","Sidney Lumet",Genere.AZIONE,1976));
		elencoFilm.add(new Film("Arizona Junior","Joel ed Ethan Coen",Genere.AZIONE,1987));
		elencoFilm.add(new Film("Lo spaccone","Robert Rossen",Genere.AZIONE,1961));
		elencoFilm.add(new Film("La finestra sul cortile","Alfred Hitchcock",Genere.AZIONE,1954));
		elencoFilm.add(new Film("La regola del gioco","Jean Renoir",Genere.AZIONE,1939));
		elencoFilm.add(new Film("Qualcuno volò sul nido del cuculo","Miloš Forman",Genere.AZIONE,1975));
		elencoFilm.add(new Film("Un uomo per tutte le stagioni","Fred Zinnemann",Genere.AZIONE,1966));
		elencoFilm.add(new Film("Un lupo mannaro americano a Londra","John Landis",Genere.AZIONE,1981));
		elencoFilm.add(new Film("L albero degli zoccoli","Ermanno Olmi",Genere.AZIONE,1981));
		elencoFilm.add(new Film("L infernale Quinlan","Orson Welles",Genere.AZIONE,1958));
		elencoFilm.add(new Film("Before Sunset - Prima del tramonto","Richard Linklater",Genere.AZIONE,2004));
		elencoFilm.add(new Film("Fitzcarraldo","Werner Herzog",Genere.AZIONE,1982));
		elencoFilm.add(new Film("Soy Cuba","Michail Kalatozov",Genere.AZIONE,1964));
		elencoFilm.add(new Film("Anchorman - La leggenda di Ron Burgundy","Adam McKay",Genere.AZIONE,2004));
		elencoFilm.add(new Film("La conversGenere.AZIONE","Francis Ford Coppola",Genere.AZIONE,1974));
		elencoFilm.add(new Film("Mezzogiorno e mezzo di fuoco","Mel Brooks",Genere.AZIONE,1970));
		elencoFilm.add(new Film("Un dollaro d onore","Howard Hawks",Genere.AZIONE,1959));
		elencoFilm.add(new Film("Crocevia della morte","Joel ed Ethan Coen",Genere.AZIONE,1990));
		elencoFilm.add(new Film("Shakespeare a colGenere.AZIONE","Bruce Robinson",Genere.AZIONE,1987));
		elencoFilm.add(new Film("Vite vendute","Henri-Georges Clouzot",Genere.AZIONE,1953));
		elencoFilm.add(new Film("La battaglia di Algeri","Gillo Pontecorvo",Genere.AZIONE,1966));
		elencoFilm.add(new Film("I figli della violenza","Luis Buñuel",Genere.AZIONE,1950));
		elencoFilm.add(new Film("La storia fantastica","Rob Reiner",Genere.AZIONE,1987));
		elencoFilm.add(new Film("Una moglie","John Cassavetes",Genere.AZIONE,1974));
		elencoFilm.add(new Film("Il silenzio degli innocenti","Jonathan Demme",Genere.AZIONE,1991));
		elencoFilm.add(new Film("Fino all ultimo respiro","Jean-Luc Godard",Genere.AZIONE,1960));
		elencoFilm.add(new Film("Pat Garrett e Billy Kid","Sam Peckinpah",Genere.AZIONE,1973));
		elencoFilm.add(new Film("La stangata","George Roy Hill",Genere.AZIONE,1973));
		elencoFilm.add(new Film("Lost in Translation - L amore tradotto","Sofia Coppola",Genere.AZIONE,2003));
		elencoFilm.add(new Film("Harvey","Henry Koster",Genere.AZIONE,1950));
		elencoFilm.add(new Film("L uomo che volle farsi re","John Huston",Genere.AZIONE,1975));
		elencoFilm.add(new Film("L ultimo dei Mohicani","Michael Mann",Genere.AZIONE,1992));
		elencoFilm.add(new Film("Il labirinto del fauno","Guillermo del Toro",Genere.AZIONE,2006));
		elencoFilm.add(new Film("La fiamma del peccato","Billy Wilder",Genere.AZIONE,1944));
		elencoFilm.add(new Film("Seven","David Fincher",Genere.AZIONE,1995));
		elencoFilm.add(new Film("La guerra lampo dei Fratelli Marx","Leo McCarey",Genere.AZIONE,1933));
		elencoFilm.add(new Film("Amadeus","Miloš Forman",Genere.AZIONE,1984));
		elencoFilm.add(new Film("Balla coi lupi","Kevin Costner",Genere.AZIONE,1990));
		elencoFilm.add(new Film("Nick mano fredda","Stuart Rosenberg",Genere.AZIONE,1967));
		elencoFilm.add(new Film("Blow Out","Brian De Palma",Genere.AZIONE,1981));
		elencoFilm.add(new Film("Qualcosa è cambiato","James L. Brooks",Genere.AZIONE,1997));
		elencoFilm.add(new Film("Biancaneve e i sette nani","David Hand",Genere.AZIONE,1937));
		elencoFilm.add(new Film("Quasi famosi","Cameron Crowe",Genere.AZIONE,2000));
		elencoFilm.add(new Film("Cyrano de Bergerac","Jean-Paul Rappeneau",Genere.AZIONE,1990));
		elencoFilm.add(new Film("Il petroliere","Paul Thomas Anderson",Genere.AZIONE,2007));
		elencoFilm.add(new Film("La scelta di Sophie","Alan J. Pakula",Genere.AZIONE,1982));
		elencoFilm.add(new Film("Shampoo","Hal Ashby",Genere.AZIONE,1975));
		elencoFilm.add(new Film("Notorious - L amante perduta","Alfred Hitchcock",Genere.AZIONE,1946));
		elencoFilm.add(new Film("Z - L orgia del potere","Costa-Gavras",Genere.AZIONE,1969));
		elencoFilm.add(new Film("Scarpette rosse","Michael Powell, Emeric Pressburger",Genere.AZIONE,1948));
		elencoFilm.add(new Film("Il braccio violento della legge","William Friedkin",Genere.AZIONE,1971));

	}
	public static List<Film> getElencoFilm() {
		return elencoFilm;
	}

		
}
